global:
  message: 'hogehoge'
  rule: all_files # all_files | file | paragraph | first | off
  format: simple

formats:
  default: ':base:(:ruby:)'
  simple: ':base:（:ruby:）'
  complex: '|:base:《:ruby:》'

rules:
  -
    text: foo
    ruby: bar
    rule: all_files
    format: default
  -
    text: hoge
    ruby: fuga
    rule: all_files
    format: default
